# Generated by Django 5.2.6 on 2025-09-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Personas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="persona",
            name="cedula",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="persona",
            name="password_hash",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="persona",
            name="username",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
