# Generated by Django 5.2.6 on 2025-09-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Personas", "0002_persona_cedula_persona_password_hash_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Boda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_boda", models.CharField(max_length=50)),
                ("fecha_boda", models.DateField()),
                ("lugar", models.CharField(max_length=200)),
                ("codigo_boda", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Regalo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=200)),
                ("precio", models.DecimalField(decimal_places=5, max_digits=10)),
                ("url", models.CharField(max_length=100)),
                ("nombre", models.CharField(default="disponible", max_length=50)),
            ],
        ),
    ]
