# Generated by Django 5.2.6 on 2025-09-26 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Personas", "0003_boda_regalo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=150, null=True)),
                ("telefono", models.CharField(max_length=20, null=True)),
                (
                    "boda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Personas.boda"
                    ),
                ),
                (
                    "invitado_registrado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Personas.persona",
                    ),
                ),
                (
                    "regalo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Personas.regalo",
                    ),
                ),
            ],
        ),
    ]
