# Generated by Django 5.2.6 on 2025-10-10 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Personas", "0004_invitado"),
    ]

    operations = [
        migrations.AddField(
            model_name="regalo",
            name="boda_id",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="Personas.boda",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="regalo",
            name="estado",
            field=models.CharField(default="disponible", max_length=50),
        ),
        migrations.AlterField(
            model_name="regalo",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("servicio", models.CharField(max_length=200)),
                ("contacto", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=20, null=True)),
                ("email", models.EmailField(max_length=150, null=True)),
                ("url", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "boda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Personas.boda"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reserva_regalo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_reserva", models.DateTimeField(auto_now_add=True)),
                ("estado", models.CharField(default="reservado", max_length=50)),
                (
                    "invitado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Personas.invitado",
                    ),
                ),
                (
                    "regalo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Personas.regalo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Servicio_proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "boda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Personas.boda"
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Personas.proveedor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contratacion_servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_contratacion", models.DateTimeField(auto_now_add=True)),
                ("estado", models.CharField(default="pendiente", max_length=50)),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Personas.proveedor",
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Personas.servicio_proveedor",
                    ),
                ),
            ],
        ),
    ]
