# Generated by Django 5.2.6 on 2025-10-10 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Personas", "0005_regalo_boda_id_regalo_estado_alter_regalo_nombre_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cancion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("artista", models.CharField(max_length=100)),
                ("fecha_agregada", models.DateTimeField(auto_now_add=True)),
                (
                    "boda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Personas.boda"
                    ),
                ),
                (
                    "invitado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Personas.invitado",
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
