# Generated by Django 5.2.6 on 2025-10-11 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Personas", "0006_cancion"),
    ]

    operations = [
        migrations.AddField(
            model_name="boda",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Personas.persona",
            ),
        ),
    ]
